packages:
  - packages/*

catalog:
  '@anthropic-ai/sdk': ^0.57.0
  '@changesets/cli': ^2.29.7
  '@google/genai': ^1.10.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@prettier/plugin-oxc': ^0.0.4
  '@types/node': ^24.7.1
  '@types/ramda': ^0.30.2
  '@vitest/coverage-v8': ^3.2.4
  dotenv: ^17.2.3
  dotenv-cli: ^10.0.0
  openai: ^5.23.2
  oxlint: ^1.22.0
  ramda: ^0.31.3
  tiktoken: ^1.0.22
  ts-inference-check: ^0.3.0
  tsup: ^8.5.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^3.2.4
  zod: ^4.1.12
  zod-validation-error: ^4.0.2
