name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (patch/minor/major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor  
        - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 10
          
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          
      - run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm run build
        
      - name: Bump versions
        run: |
          cd packages/instructor-stream
          npm version ${{ inputs.version }}
          cd ../providers
          npm version ${{ inputs.version }}
        
      - name: Commit version changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/*/package.json
          git commit -m "chore: bump versions to $(cd packages/instructor-stream && node -p 'require(\"./package.json\").version')"
          git push
        
      - name: Publish packages
        run: |
          cd packages/instructor-stream
          npm publish --access public
          cd ../providers  
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}