name: Publish to NPM

on:
  push:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.check.outputs.should-publish }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if version changed
        id: check
        run: |
          # Check if any package.json version changed in the last commit
          if git diff HEAD~1 HEAD --name-only | grep -q "packages/.*/package.json"; then
            if git diff HEAD~1 HEAD -- packages/*/package.json | grep -q '"version"'; then
              echo "should-publish=true" >> $GITHUB_OUTPUT
            else
              echo "should-publish=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should-publish=false" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: detect-changes
    if: needs.detect-changes.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 10
          
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          
      - run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm run build
        
      - name: Publish packages
        run: |
          cd packages/instructor-stream
          npm publish --access public
          cd ../providers  
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}