name: Publish

on:
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {}
jobs:
  publish:
    if: github.repository == 'CogniformAI/instructor-stream-js' && github.event.pull_request.merged == true && (startsWith(github.head_ref, 'changeset-release/main') || startsWith(github.head_ref, '_publish-trigger'))
    permissions:
      contents: write
      pull-requests: write

    name: Publish packages
    runs-on: ubuntu-latest
    environment: Publish

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish packages & create release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-packages
          createGithubReleases: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
