name: Test Main
on:
  push:
    branches:
      - main
jobs:
  test-main:
    if: github.repository == 'CogniformAI/instructor-stream-js' && github.ref == 'refs/heads/main'
    name: run-tests
    runs-on: ubuntu-latest
    env:
      RUN_PROVIDER_TESTS: false
      RUN_BENCHMARK_TESTS: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm run type-check
      - run: pnpm run lint
      - run: pnpm test
